# site data for RSS feed
name: Neilrenicker.com
description: The design, development, and workflow blog of Neil Renicker
url: http://neilrenicker.com

# build:
source: templates
destination: dist

permalink: /:categories/:title.html

# configuration:
timezone: America/Kentucky/Louisville